# step 1 : Build with JDK
FROM eclipse-temurin:17-jdk-jammy AS build
WORKDIR /app
COPY . .
#avoid mvnw permission denied and check jar file in target folder 
RUN chmod +x ./mvnw && ./mvnw clean package -DskipTests && ls -l /app/target/

# step 2 : Run with JRE
FROM eclipse-temurin:17-jre-jammy AS runtime
WORKDIR /app

#copy dynamically the generated jar file from the build stage and rename it to app.jar
COPY --from=build /app/target/*.jar /app/app.jar

#expose port 8008
EXPOSE 8008

# command to run the application
ENTRYPOINT ["java", "-jar", "/app/app.jar"]
